---
title: "SEMANA_12"
author: "GRUPO 6"
format: html
editor: visual
---

## Calcular las Medidas de Dispersión (Varianza, Desviación estándar, Rango, Rango intercuartílico) y de posición (Cuartiles), script para visualizar las 6

```{r}
#1 SE IMPORTA EL ARCHIVO CON EL CUAL SE VA A TRABAJAR, EN ESTE CASO EL ARCHIVO AUTISMO, LUEGO SE COPIA UNA PARTE DEL CÓDIGO Y SE LLEVA AL R SCRIPT
data<- read_csv("C:/Users/s9343/Downloads/autismo.csv")

```

```{r}
#2 PARA HALLAR LA VARIANZA, SE UTILIZA EL CÓDIGO CORRESPONDIENTE Y AL FINAL DE “VAR” DEL PARÉNTESIS SE PRESIONA CTRL + ENTER PARA OBSERVAR EL RESULTADO EN LA CONSOLA
#VARIANZA
var(data$Puntuacion_P1,na.rm =  TRUE)
```

```{r}
#3 PARA HALLAR LA DESVIACIÓN ESTÁNDAR, SE UTILIZA EL CÓDIGO CORRESPONDIENTE Y AL FINAL DE “SD” DEL PARÉNTESIS SE PRESIONA CTRL + ENTER PARA OBSERVAR EL RESULTADO EN LA CONSOLA
sd(data$Puntuacion_P1,na.rm = TRUE)
```

```{r}
#4 PARA HALLAR EL RANGO, SE UTILIZA EL CÓDIGO CORRESPONDIENTE Y AL FINAL DE “RANGE” DEL PARÉNTESIS SE PRESIONA CTRL + ENTER PARA OBSERVAR EL RESULTADO EN LA CONSOLA
range(data$Puntuacion_P1,na.rm = TRUE)
```

```{r}
#5 PARA HALLAR EL RANGO INTERCUARTÍLICO, SE UTILIZA EL CÓDIGO CORRESPONDIENTE Y AL FINAL DE “IQR” DEL PARÉNTESIS SE PRESIONA CTRL + ENTER PARA OBSERVAR EL RESULTADO EN LA CONSOLA
IQR(data$Puntuacion_P1,na.rm = TRUE)
```

```{r}
#6 PARA HALLAR LAS MEDIDAS DE POSICIÓN (CUARTILES), SE UTILIZA EL CÓDIGO CORRESPONDIENTE Y AL FINAL DE “QUANTILE” DEL PARÉNTESIS SE PRESIONA CTRL + ENTER PARA OBSERVAR EL RESULTADO EN LA CONSOLA
quantile(data$Puntuacion_P1,probs = c (0.25,0.50,0.75,0.90),na.rm = TRUE)
```

```{r}
#7 PARA VISUALIZAR LAS 6 PRIMERAS FILAS, SE UTILIZA EL CÓDIGO CORRESPONDIENTE Y AL FINAL DE “HEAD” DEL PARÉNTESIS SE PRESIONA CTRL + ENTER PARA OBSERVAR EL RESULTADO EN LA CONSOLA
head(data)
```

```{r}
#8 PARA REALIZAR UN RESUMEN GENERAL DE TODAS LAS MEDIDAS, SE UTILIZA EL CÓDIGO CORRESPONDIENTE Y AL FINAL DE “SUMMARY” DEL PARÉNTESIS SE PRESIONA CTRL + ENTER PARA OBSERVAR EL RESULTADO EN LA CONSOLA
summary(data)
```
